### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by sehkmg** [ai-tf/relationExtraction#1]
# TODO List

### General
- [ ] TPLinker, CasRel 호환 dataset 제작. (https://github.com/ai-tf/relationExtraction/tree/main/data/new)
- [ ] Full NYT, WebNLG로 CasRel 다시 평가.
- [ ] TPLinker reproduce.
- [ ] Entity noising 개선.
- [ ] inconsistent한 case인데 억지로 만들어낸 경우는 없는지 case study 진행.
- [ ] 비슷한 paper search 다시 진행.

### Issue: Original test set의 경우 모든 case에 대해 baseline이 aug나 noise보다 잘 나온다.
- [ ] case study 진행.
- [ ] valid의 statistics 확인.
- [ ] Unseen train statistics 찍어보고 aug에서 떨어지는 이유 분석.
- [ ] 모델 학습 description 공유.
- [ ] Full NYT, WebNLG를 이용한 CasRel에서도 같은 문제가 발생하는지 확인.
- [ ] TPLinker도 같은 문제가 발생하는지 확인.
